apiVersion: v1
kind: Secret
metadata:
  name: infraaudit-env
  labels:
    app: infraaudit
    managed-by: infraaudit
    type: env
# NOTE: Sensitive values are included below for illustration. In real projects,
#       do NOT commit plaintext secrets to version control. Instead, create the
#       secret at deploy-time with `kubectl create secret generic infraaudit-env --from-env-file=.env`.
#       If you keep this manifest in Git, consider using Sealed Secrets or SOPS.
type: Opaque
stringData:
  OPENAI_API_KEY: ysk-proj-McnbNR2qMVExbBHDUWdLJI9NVyGNkDX1CEoWuArLWEwibi043MCYiB5I2Dhk9DJIIZUawMkM5QT3BlbkFJC8E4yVlmghChuR8z3kVC7xYZwppml4Ix5mgUK_wWLoXW6HE7StUEdrDDIqGkf4TxW6eiugRtsA
  SLACK_BOT_TOKEN: nT4UjnzVH2cZFChyzsam8wRx
  SLACK_CHANNEL_ID: A08R84G3BRD
  STRIPE_SECRET_KEY: sk_test_51RNBFq2c41yfi4sIHNsx75wH8wut653p8BpnjLkX3R2AxZ8eHcpwbwqoBTtdZgVs24gdxI5EqocaeIzlBMhSE9J100NXdsyTpt
  VITE_STRIPE_PUBLIC_KEY: pk_test_51RNBFq2c41yfi4sIf6R9IFhQngKq8LVirF8iR3RytsKZUIyLdD2tPDTgjCCiXhIAxndeX98HV5f4HgKK0axvoJQF006BVMbimn
  SESSION_SECRET: WrIp1aS66Bb5Z1SACwiQqffAQCa//eWDSyw4FJvAiN2h9hT2Ius628bb3eWYQP5vinCGVwNQTMdhZMFUpbn1gw==
  DATABASE_URL: postgresql://pratik:infraaudit@postgres:5432/cloudwatchdog
  PGDATABASE: cloudwatchdog
  PGHOST: postgres
  PGPORT: "5432"
  PGUSER: pratik
  PGPASSWORD: infraaudit 