apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "infraaudit.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "infraaudit.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

data:
{{- range $key, $value := .Values.config }}
  {{ $key }}: "{{ $value }}"
{{- end }} 